image: gcc

build:
  stage: build

  before_script:
    - apt update && apt -y install make autoconf
  script:
    - g++ tictactoe.cpp -o tictactoe
    - g++ foodtruck.cpp -o foodtruck
  artifacts:
    paths:
      - tictactoe
      - foodtruck
  cache:
    paths:
      - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo Run anything here
