image: gcc

build:
  stage: build

  before_script:
    - apt update && apt -y install make autoconf
  script:
    - g++ tictactoe.cpp -Wall -O2 -o tictactoe
    - g++ tictacmoves.cpp -Wall -O2 -o tictacmoves
    - g++ foodmodel.cpp -Wall -O2 -o foodmodel
    - g++ areview.cpp -Wall -O2 -o areview
    - g++ csvwrite.cpp -Wall -O2 -o csvwrite
    - g++ csvread.cpp -Wall -O2 -o csvread
    - g++ biometrics.cpp -Wall -O2 -o biometrics
    - g++ inherit.cpp -Wall -O2 -o inherit
    - g++ dynamic.cpp -Wall -O2 -o dynamic
    - g++ multiinherit.cpp -Wall -O2 -o multiinherit
    - g++ account.cpp -Wall -O2 -o account
    - g++ operators.cpp -Wall -O2 -o operators
    - g++ template.cpp -Wall -O2 -o template
    - cd FoodTruck
    - make
    - cd ..
    - cd examples
    - g++ file.cpp -o file
    - g++ metastruct.cpp -Wall -O2 -o metastruct
    - cc pointies.c -O2 -o pointies
    - g++ polymorph.cpp -Wall -O2 -o polymorph
    - g++ string.cpp -Wall -O2 -o string
    - g++ struct.cpp -Wall -O2 -o struct
    - g++ substr.cpp -Wall -O2 -o substr
    - g++ vec2.cpp -Wall -O2 -o vec
    - cd ..
  artifacts:
    paths:
      - tictactoe
      - tictacmoves
      - foodmodel
      - areview
      - csvwrite
      - csvread
      - biometrics
      - inherit
      - dynamic
      - multiinherit
      - account
      - operators
      - template
      - FoodTruck/foodtruck
      - examples/file
      - examples/metastruct
      - examples/pointies
      - examples/polymorph
      - examples/string
      - examples/struct
      - examples/substr
      - examples/vec
  cache:
    paths:
      - "*.o"
      - "FoodTruck/*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo Run anything here

