image: gcc

build:
  stage: build

  before_script:
    - apt update && apt -y install make autoconf
  script:
    - g++ tictactoe.cpp -o tictactoe
    - g++ tictacmoves.cpp -o tictacmoves
    - g++ foodmodel.cpp -o foodmodel
    - g++ areview.cpp -o areview
    - g++ csvwrite.cpp -o csvwrite
    - g++ csvread.cpp -o csvread
    - g++ biometrics.cpp -o biometrics
    - g++ inherit.cpp -o inherit
    - cd FoodTruck
    - make
    - cd ..
    - cd examples
    - g++ file.cpp -o file
    - g++ metastruct.cpp -o metastruct
    - cc pointies.c
    - g++ polymorph.cpp -o polymorph
    - g++ string.cpp -o string
    - g++ struct.cpp -o struct
    - g++ substr.cpp -o substr
    - g++ vec2.cpp -o vec
    - cd ..
  artifacts:
    paths:
      - tictactoe
      - tictacmoves
      - foodmodel
      - areview
      - csvwrite
      - csvread
      - biometrics
      - inherit
      - FoodTruck/foodtruck
      - examples/file
      - examples/metastruct
      - examples/a.out
      - examples/polymorph
      - examples/string
      - examples/struct
      - examples/substr
      - examples/vec
  cache:
    paths:
      - "*.o"
      - "FoodTruck/*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo Run anything here

